global:
  # How frequently to scrape targets by default.
  scrape_interval: 30s

  # How long until a scrape request times out.
  scrape_timeout: 15s

  # How frequently to evaluate rules.
  evaluation_interval: 10m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']